mums_assistant:
  mums_assistant_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5

    gains:
      joint_1: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_2: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_3: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_4: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_5: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}


  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - gripper_joint_1
    gains:
      gripper_joint_1: {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}